name: Deploy

# Triggers the workflow on pull requests to the master branch
on: 
    pull_request: 
      branches: 
      — master 

# The workflow jobs 
jobs:

    # Build Job
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
  
      # The build steps
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0' 
      
      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          
      # Run build of the application
      - name: Run build
        run: go build . 
        
      # Run vet & lint on the code
      - name: Run vet & lint
        run: |
          go vet .
          golint .
      
      # Run testing on the code
      - name: Run testing
        run: go test -v
      

    # # Deploy Job
    # deploy:
    #   # The type of runner that the job will run on
    #   runs-on: ubuntu-latest
    #   needs: [build] # Only run this workflow when "build" workflow succeeds
    #   if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
    #   steps:
    #   - uses: actions/checkout@v2
  
    #   # Deploy to Docker registry
    #   - name: Deploy to Docker registry
    #     uses: docker/build-push-action@v1
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
    #       repository: wilsontanwm/gosimple
    #       tag_with_ref: true
