name: Build and package logger

on:
  push:
    branches:
#    - master
  pull_request:
    branches:
    - master
    - develop

jobs:

  # Build the source
  build:
    runs-on: ubuntu-latest
    
    # Variables for the build job
    env:
      build-file: 'logger'
      build-dir: '${{ github.workspace }}/bin'
      zip-file: 'logger.zip'
      zip-dir: '${{ github.workspace }}/zip'
    
    # Build steps
    steps:
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0' 
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
      
    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet .
        golint .
        
    # Run go build 
    - name: Run build
      run: |
        echo 'Build file: ${{ env.build-dir }}/${{ env.build-file }}'
        mkdir -p ${{ env.build-dir }}
        go build -o '${{ env.build-dir }}/${{ env.build-file }}'
        
    # Zip build binary
    - name: Zip build
      run: |
        echo 'Zip file: ${{ env.zip-dir }}/${{ env.zip-file }}'
        mkdir -p ${{ env.zip-dir }}
        zip -vr '${{ env.zip-dir }}/${{ env.zip-file }} ${{ env.build-dir }}/${{ env.build-file }}'
      
    # Run testing on the code
    - name: Run testing
      run: go test -v
