name: Build and package logger

on:
  push:
    branches:
#    - master
  pull_request:
    branches:
    - master
    - develop

jobs:

  # Build the source
  build:
    runs-on: ubuntu-latest
    
    # Variables for the build job
    env:
      build-file: 'logger'
      build-dir: '${{ github.workspace }}/bin'
    
    # Build steps
    steps:
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0' 
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
      
    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet .
        golint .
        
    # Run build of the application
    - name: Run build
      run: |
        mkdir -p ${{ env.build-dir }}
        go build -o '${{ env.build-dir }}/${{ build-file }}'
        zip -vr /tmp/logger.zip /tmp/bin/*
      
    # Run testing on the code
    - name: Run testing
      run: go test -v
