#######################################################
# This workflow deletes any workflow artefacts that 
# are older than 1 day. This workflow gets triggered 
# by the cron schedule.
#
#######################################################

name: Perform cleanup

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        uses: glassechidna/artifact-cleaner@master
        with:
          minimumAge: 86400 # all artifacts at least one day old
