#######################################################
# This workflow gets triggered by the creation of a
# new release in Github (eg push of tag). The
# workflow uploads a tar file containing the binary
# to the release. It performs the following tasks:
#
#    - log the git branch/commit details
#    - install Go v1.15
#    - run go vet/lint
#    - install CodeQL
#    - compile the code
#    - run CodeQL analysis
#    - tar the compiled binary
#    - run any go test cases
#    - upload the tar file to the release
#
#######################################################

name: Create release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Variables for the build job
    env:
      build-file: 'logger'
      build-dir: '${{ github.workspace }}/bin'
      tar-file: 'logger.tar'
      tar-dir: '${{ github.workspace }}/tar'
    
    # Build steps
    steps:
    - uses: actions/checkout@v2
    
    # Log basic info
    - name: Log git event info
      run: |
        echo Event: ${{ github.event_name }}
        echo Git Ref: ${{ github.ref }}
        echo Git SHA: ${{ github.sha }}
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0' 
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
      
    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet .
        golint .
        
    # Setup CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: go
        
    # Run go build 
    - name: Run build
      run: |
        mkdir -p ${{ env.build-dir }}
        go build -o ${{ env.build-dir }}/${{ env.build-file }}
        ls -al ${{ env.build-dir }}
        
    # Run CodeQL analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    # Tar build binary
    - name: Tar build
      run: |
        cd ${{ env.build-dir }}
        mkdir -p ${{ env.tar-dir }}
        tar -cvf ${{ env.tar-dir }}/${{ env.tar-file }} ./${{ env.build-file }}
        ls -al ${{ env.tar-dir }}

    # Run any test cases
    - name: Run test cases
      run: go test ./... -v
      
    # Upload release asset
    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.tar-dir }}/${{ env.tar-file }}
        asset_name: ${{ env.tar-file }}
        asset_content_type: application/x-tar
